coverage:
  status:
    project:
      default:
        # We don't gate anything based on potentially flaky code
        # coverage reports.
        informational: true
    patch:
      default:
        informational: true
